### ISSUE TITLE
Interoperability

### ISSUE THREAD

**Issue by alienatorZ** [SkPhilipp/mqtt-drpc#3]
How would I use a service that is using this library, from some other language such as node.js?

Thanks!

**Comment by SkPhilipp** [comment]
Hi there,

The protocol is very a simple request & response. I haven't written anything about the way the calls are made yet, but it's just JSON over MQTT, I'll have it documented in a few days time. For talking over MQTT, I'd recommend http://www.eclipse.org/paho/

**Comment by SkPhilipp** [comment]
I've added a description of the protocol to the readme. If this description isn't enough please reopen this ticket.
